//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dpark.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dpark.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry again.
        /// </summary>
        internal static string btnTxtRerty {
            get {
                return ResourceManager.GetString("btnTxtRerty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions.
        /// </summary>
        internal static string Get_Directions {
            get {
                return ResourceManager.GetString("Get_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string lblOption {
            get {
                return ResourceManager.GetString("lblOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Application?.
        /// </summary>
        internal static string Leave_Application {
            get {
                return ResourceManager.GetString("Leave_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Leave.
        /// </summary>
        internal static string Leave_Mapping_Yes {
            get {
                return ResourceManager.GetString("Leave_Mapping_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to leave the Dpark app and get directions?.
        /// </summary>
        internal static string Leave_MappingDirections {
            get {
                return ResourceManager.GetString("Leave_MappingDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainTabs_About {
            get {
                return ResourceManager.GetString("MainTabs_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Space.
        /// </summary>
        internal static string MainTabs_FlagSpace {
            get {
                return ResourceManager.GetString("MainTabs_FlagSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MainTabs_Search {
            get {
                return ResourceManager.GetString("MainTabs_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to launch application again. If the error appears, contact the developers..
        /// </summary>
        internal static string msgErrLoading {
            get {
                return ResourceManager.GetString("msgErrLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NetworkConnection_Alert_Confirm {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires access to remote data, but you don&apos;t seem to currently have a network connnection. Check your connection and try again..
        /// </summary>
        internal static string NetworkConnection_Alert_Message {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NetworkConnection_Alert_Title {
            get {
                return ResourceManager.GetString("NetworkConnection_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’d love to hear from you!  If the space doesn&apos;t exist or innacurate. Please tap on the flag icon to send us a note..
        /// </summary>
        internal static string Option_FlagSpace {
            get {
                return ResourceManager.GetString("Option_FlagSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data.
        /// </summary>
        internal static string titleErrLoading {
            get {
                return ResourceManager.GetString("titleErrLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Internet available.
        /// </summary>
        internal static string txtProcessCheckInternet {
            get {
                return ResourceManager.GetString("txtProcessCheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server.
        /// </summary>
        internal static string txtProcessConnection {
            get {
                return ResourceManager.GetString("txtProcessConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data.
        /// </summary>
        internal static string txtProcessLoadingData {
            get {
                return ResourceManager.GetString("txtProcessLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check internet connection.
        /// </summary>
        internal static string txtRertyCheckInternet {
            get {
                return ResourceManager.GetString("txtRertyCheckInternet", resourceCulture);
            }
        }
    }
}
